---

- name: add gravity lists
  command:
    argv:
      - sqlite3
      - "{{ pihole_etc_dir }}/gravity.db"
      - "INSERT OR REPLACE INTO adlist (id, address, enabled, comment) VALUES ((SELECT id FROM adlist WHERE address = '{{ item.address }}'), '{{ item.address }}', {{ item.enabled | default(true) }}, '{{ item.comment }}');"
  notify: update pi-hole gravity
  with_items: "{{ pihole_gravity_lists }}"
