# handlers file
---

- name: update pi-hole
  command: "{{ pihole_bin_path }} updatePihole"

- name: reconfigure pi-hole dns
  command: "{{ pihole_bin_path }} -a -i {{ pihole_setupvars_dnsmasq_listening }}"

- name: update pi-hole gravity
  command: "{{ pihole_bin_path }} -g"

- name: restart pi-hole dns
  command: "{{ pihole_bin_path }} restartdns"
